In [1]:
import pandas as pd 
import numpy as np
import os
import sys
import h5py

In [2]:
achile_fpath = "/raid/shadab/prateek/genedisco/gd_cache/achilles.csv"

In [3]:
df = pd.read_csv(achile_fpath)

In [4]:
df

,DepMap_ID,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
0,ACH-000004,0.181332,0.089101,-0.193867,-0.024587,0.038458,-0.181824,0.351672,-0.440073,0.292582,...,-0.124218,-0.469306,NaN,NaN,0.257361,0.244834,-0.408512,0.284734,0.226412,-0.149566
1,ACH-000005,-0.076383,0.245190,0.191238,0.153008,-0.197035,-0.323295,0.252522,-0.571498,-0.068945,...,-0.212442,-0.426151,-0.068295,0.031635,0.205469,-0.068536,-0.092858,0.074640,0.028779,-0.264840
2,ACH-000007,0.102195,0.092449,-0.045926,0.171892,0.140561,0.170971,0.086060,-0.432320,0.010664,...,-0.083183,-0.269196,0.101146,0.277820,0.208814,0.001393,-0.327514,0.048714,-0.372854,-0.433157
3,ACH-000009,0.142342,-0.033126,-0.051224,0.060560,0.116002,-0.010044,0.104725,-0.610481,0.181508,...,-0.277264,-0.307018,0.044741,0.201551,0.083866,0.052208,-0.574719,0.218682,-0.074750,-0.551760
4,ACH-000011,0.280082,0.088898,0.032321,0.446598,-0.037188,-0.228207,0.110942,-0.406541,0.153979,...,-0.385241,-0.476314,-0.000984,0.013225,0.294002,0.137939,-0.245951,0.111173,-0.227417,-0.349564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,ACH-001864,0.142146,0.091203,-0.065846,0.201162,-0.050845,0.022068,0.193640,-0.513619,0.134084,...,-0.055064,-0.613773,-0.005751,-0.078028,0.103815,0.198407,-0.092758,0.138445,-0.062689,-0.326322
781,ACH-001955,0.083969,0.000861,-0.165567,0.075938,0.027625,-0.031624,0.187136,-0.438159,0.065415,...,-0.061303,-0.480877,-0.175050,-0.055326,0.119064,0.128853,-0.219467,0.145578,-0.393955,-0.173093
782,ACH-001956,-0.069368,0.107544,0.014267,0.210277,-0.074516,-0.007061,0.127842,-0.417042,0.025187,...,-0.030968,-1.029906,0.057301,0.053442,0.137078,0.138346,-0.262405,0.150346,-0.057899,-0.303403
783,ACH-001957,0.059190,0.000148,0.081399,0.204926,-0.026208,-0.126875,-0.119015,-0.502196,0.124432,...,-0.142745,-0.668730,-0.122638,0.006206,0.086469,0.219856,0.084723,0.137358,-0.073958,-0.417795
784,ACH-001959,0.140551,0.108885,-0.161035,0.100741,-0.010445,-0.070118,0.165294,-0.555645,0.062566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.describe()

,A1BG (1),A1CF (29974),A2M (2),A2ML1 (144568),A3GALT2 (127550),A4GALT (53947),A4GNT (51146),AAAS (8086),AACS (65985),AADAC (13),...,ZWILCH (55055),ZWINT (11130),ZXDA (7789),ZXDB (158586),ZXDC (79364),ZYG11A (440590),ZYG11B (79699),ZYX (7791),ZZEF1 (23140),ZZZ3 (26009)
count,785.000000,785.000000,785.000000,785.000000,785.000000,785.000000,785.000000,785.000000,785.000000,785.000000,...,784.000000,784.000000,765.000000,765.000000,784.000000,784.000000,784.000000,784.000000,784.000000,773.000000
mean,0.111220,0.069680,-0.056921,0.179913,-0.035631,-0.043862,0.118065,-0.514208,0.078293,0.162343,...,-0.107996,-0.549710,0.017189,0.061163,0.105993,0.077901,-0.183500,0.125821,-0.166310,-0.385503
std,0.124133,0.122120,0.107535,0.121332,0.144706,0.129073,0.117547,0.179865,0.129223,0.132160,...,0.163066,0.241104,0.153428,0.167594,0.137654,0.126544,0.137453,0.135152,0.151205,0.167825
min,-0.499506,-0.749276,-0.495425,-0.353756,-0.700440,-0.674052,-0.236621,-1.479991,-0.740168,-0.459333,...,-0.921473,-1.410735,-0.750230,-1.442541,-0.424745,-0.343132,-0.864628,-0.652634,-0.660907,-1.226509
25%,0.045839,0.002854,-0.116036,0.112087,-0.115174,-0.118811,0.047071,-0.614526,0.012534,0.093932,...,-0.207209,-0.709903,-0.075915,-0.022587,0.032617,-0.000236,-0.259537,0.056145,-0.247496,-0.491332
50%,0.115929,0.073359,-0.057549,0.181415,-0.031828,-0.041474,0.118727,-0.501193,0.083386,0.162003,...,-0.106649,-0.566737,0.021541,0.066011,0.107525,0.078126,-0.180741,0.139571,-0.160806,-0.380903
75%,0.187081,0.135135,0.003703,0.237559,0.045149,0.029704,0.189093,-0.398100,0.154924,0.235425,...,-0.005638,-0.395731,0.112651,0.160441,0.184274,0.149775,-0.106933,0.215093,-0.082650,-0.286604
max,0.798506,0.530583,0.581334,1.016989,0.774305,0.696779,0.765730,0.018836,0.696792,0.820783,...,0.677736,0.578194,0.950778,0.790275,1.119069,1.210021,0.513621,0.505003,0.823686,0.374475

In [6]:
df_cols = list(df.columns.to_list())[1:]
df_cols = [x.split(" (")[0] for x in df_cols]
print(df_cols[:10])

print("Number pf df_cols: ", len(df_cols))

['A1BG', 'A1CF', 'A2M', 'A2ML1', 'A3GALT2', 'A4GALT', 'A4GNT', 'AAAS', 'AACS', 'AADAC']
Number pf df_cols:  18119

Reading the h5 files...

In [14]:
achile_h5path = "/raid/shadab/prateek/genedisco/gd_cache/achilles.h5"
string_h5path = "/raid/shadab/prateek/genedisco/gd_cache/string_embedding.h5"
ccle_h5path = "/raid/shadab/prateek/genedisco/gd_cache/ccle_protein_quantification.h5"
ifng_fpath = "/raid/shadab/prateek/genedisco/gd_cache/schmidt_2021_ifng.h5"

def allkeys(obj):
    "Recursively find all keys in an h5py.Group."
    keys = (obj.name,)
    if isinstance(obj, h5py.Group):
        for key, value in obj.items():
            if isinstance(value, h5py.Group):
                keys = keys + allkeys(value)
            else:
                keys = keys + (value.name,)
    return keys

In [15]:
# achile_h5

# open the file as 'f'
achile_colnames = None
achile_covariates = None
achile_rownames = None

##Achilles

with h5py.File(achile_h5path, 'r') as f:
    # achile_h5_data = f['default']
    tempKeys = allkeys(f)
    print(tempKeys)
    
    for k in tempKeys:
        print(f"for k={k} \t value={f.get(k)}")
    
    achile_colnames = list(np.array(f.get('colnames')))
    achile_covariates = np.array(f.get('covariates'))
    achile_rownames = list(np.array(f.get('rownames')))
    
    achile_colnames = [x.decode("utf-8") for x in achile_colnames]
    achile_rownames = [x.decode("utf-8") for x in achile_rownames]
    
string_colnames = None
string_covariates = None
string_rownames = None

##String

with h5py.File(string_h5path, 'r') as f:
    # achile_h5_data = f['default']
    tempKeys = allkeys(f)
    print(tempKeys)
    
    for k in tempKeys:
        print(f"for k={k} \t value={f.get(k)}")
    
    string_colnames = list(np.array(f.get('colnames')))
    string_covariates = np.array(f.get('covariates'))
    string_rownames = list(np.array(f.get('rownames')))
    
    string_colnames = [x.decode("utf-8") for x in string_colnames]
    string_rownames = [x.decode("utf-8") for x in string_rownames]
    
ccle_colnames = None
ccle_covariates = None
ccle_rownames = None

##ccle

with h5py.File(ccle_h5path, 'r') as f:
    # achile_h5_data = f['default']
    tempKeys = allkeys(f)
    print(tempKeys)
    
    for k in tempKeys:
        print(f"for k={k} \t value={f.get(k)}")
    
    ccle_colnames = list(np.array(f.get('colnames')))
    ccle_covariates = np.array(f.get('covariates'))
    ccle_rownames = list(np.array(f.get('rownames')))
    
    ccle_colnames = [x.decode("utf-8") for x in ccle_colnames]
    ccle_rownames = [x.decode("utf-8") for x in ccle_rownames]

('/', '/colnames', '/covariates', '/rownames')
for k=/ 	 value=<HDF5 group "/" (3 members)>
for k=/colnames 	 value=<HDF5 dataset "colnames": shape (785,), type "|O">
for k=/covariates 	 value=<HDF5 dataset "covariates": shape (17660, 785), type "<f8">
for k=/rownames 	 value=<HDF5 dataset "rownames": shape (17660,), type "|O">
('/', '/colnames', '/covariates', '/rownames')
for k=/ 	 value=<HDF5 group "/" (3 members)>
for k=/colnames 	 value=<HDF5 dataset "colnames": shape (799,), type "|O">
for k=/covariates 	 value=<HDF5 dataset "covariates": shape (17975, 799), type "<f8">
for k=/rownames 	 value=<HDF5 dataset "rownames": shape (17975,), type "|O">
('/', '/colnames', '/covariates', '/rownames')
for k=/ 	 value=<HDF5 group "/" (3 members)>
for k=/colnames 	 value=<HDF5 dataset "colnames": shape (420,), type "|O">
for k=/covariates 	 value=<HDF5 dataset "covariates": shape (11945, 420), type "<f8">
for k=/rownames 	 value=<HDF5 dataset "rownames": shape (11945,), type "|O">

In [16]:
print(f"Achille: {achile_covariates.shape} \t string: {string_covariates.shape} \t ccle: {ccle_covariates.shape}")

Achille: (17660, 785) 	 string: (17975, 799) 	 ccle: (11945, 420)

In [21]:
print("--- Achile ---")
print(achile_colnames[:5])
print(achile_rownames[:5])
print(achile_covariates.shape)

print("--- String ---")
print(string_colnames[:5])
print(string_rownames[:5])
print(string_covariates.shape)

print("--- ccle ---")
print(ccle_colnames[:5])
print(ccle_rownames[:5])
print(ccle_covariates.shape)

--- Achile ---
['ACH-000004', 'ACH-000005', 'ACH-000007', 'ACH-000009', 'ACH-000011']
['A1BG', 'A1CF', 'A2M', 'A2ML1', 'A3GALT2']
(17660, 785)
--- String ---
['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4']
['A1BG', 'A1CF', 'A2M', 'A2ML1', 'A4GALT']
(17975, 799)
--- ccle ---
['TenPx01_Peptides', 'TenPx02_Peptides', 'TenPx03_Peptides', 'TenPx04_Peptides', 'TenPx06_Peptides']
['', 'A1CF', 'A2M', 'A2ML1', 'AAAS']
(11945, 420)

In [ ]:
ifng_colnames = None
ifng_covariates = None
ifng_rownames = None
with h5py.File(ifng_fpath, 'r') as f:
    tempKeys = allkeys(f)
    print(tempKeys)
    
    for k in tempKeys:
        print(f"for k={k} \t value={f.get(k)}")
        
    ifng_colnames = list(np.array(f.get('colnames')))
    ifng_covariates = np.array(f.get('covariates'))
    ifng_rownames = list(np.array(f.get('rownames')))
    
    ifng_colnames = [x.decode("utf-8") for x in ifng_colnames]
    ifng_rownames = [x.decode("utf-8") for x in ifng_rownames]

In [ ]:
print("colnames: ",ifng_colnames[:10])
print("rownames: ",ifng_rownames[:10])
print("covariates: ",ifng_covariates[:10])

In [ ]:
hgnc_mapfpath = "/raid/shadab/prateek/genedisco/gd_cache/hgnc_mapping.tsv"

hgnc_df = pd.read_csv(hgnc_mapfpath, sep="\t")

In [ ]:
hgnc_df